apiVersion: apps/v1
kind: Deployment
metadata:
  name: abc-tech-deploy
  labels:
    app: abc_deploy
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: abc_deploy
  template:
    metadata:
      labels:
        app: abc_deploy
    spec:
      containers:
      - name: abc-app
        image: gnanim07/abc_tech:latest
        ports:
        - containerPort: 8080
