apiVersion: apps/v1
kind: Deployment
metadata:
  name: abc-tech-deploy
spec:
  selector:
    matchLabels:
      app: abc_deploy
  replicas: 1
  template:
    metadata:
      labels:
        app: abc_deploy
    spec:
      containers:
      - name: abc-app
        image: gnanendrame/abc_tech:latest
        ports:
        - containerPort: 8080
