- name: install docker on the server
  hosts: all
  become: yes
  tasks:
  - name: install
    package:
      name: docker.io
      state: present
  - name: start docker
    service:
      name: docker
      state: started
      enabled: true
