apiVersion: v1
kind: Service
metadata:
  name: abc-tech-lb
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: abc_deploy       
  ports:
    - name: http
      port: 80                  
      targetPort: 8080          
      protocol: TCP
